### ISSUE TITLE
[1.12.2] Killing Skeletons and Iron Golems causes crash

### ISSUE THREAD

**Issue by Snuggle** [iChun/Shatter#28]
Hello! I've been using your mod for a while and I've just noticed that killing a skeleton causes an instant crash. I have no clue why this is happening and it's not happening for players, creepers, zombies or any other mobs I've tested.

This is 100% reproducible in multiplayer, single-player etc. 
It doesn't seem to matter how the skeleton dies. I've crashed from killing skeletons by sword, by hand, by fire and by lava. It just crashes as soon as it tries to render the skeleton's shatter.

Totally open to questions and I'm happy to provide more details/record a YouTube video if needed. 🙂 

**Full Crash Log:** https://pastebin.com/Mg8kssD9 :heart:

**Comment by iChun** [comment]
Why are some of my mods not from official sources or have been renamed? 🤔

**Comment by Snuggle** [comment]
@iChun, I think I downloaded iChunUtil from www.9minecraft.net and the rest from your Curse profile. (Could be mistaken)

http://www.9minecraft.net/ichun-util-mod/
https://minecraft.curseforge.com/members/iChun/projects

**Comment by iChun** [comment]
Please try not to do that in the future. I don't know what they could have
done to the files which you could be using right now. Always try to
download from official sources if possible.

**Comment by Snuggle** [comment]
@iChun, which mods have unusual filenames, so I can replace them?

Or do you not count Curse as an official source, too?

**Comment by iChun** [comment]
I meant those from Minecraft9. Curse Forge is an official source, I upload
the files there myself. My file names always go by <mod name, no
spaces>-<Minecraft version>-<mod version>-.jar

**Comment by Snuggle** [comment]
Okiedokie. Thank you for that, iChun.

I've re-downloaded Morph and iChunUtil from Curse Forge and the bug still occurs.
Perhaps this is due to the new quiver that skeletons have in newer Minecraft versions? The crash is complaining about `createCubeInfoFromModelBox`. No clue. 😋

Here's a new crash log w/ re-downloaded mods: https://pastebin.com/QeVv0CsZ

**Comment by iChun** [comment]
Yeah I was gonna look into the crash anyways. The crash looks legit, I just noticed some of my mods were from unofficial sources and wanted to discourage that first.

**Comment by iChun** [comment]
It's not crashing without just my mods installed. Morph will probably have this issue as well. potentially a mod conflict. I'll try patch the crash anyways.

**Comment by Snuggle** [comment]
I've gone through and enable/disabled my mods to find which actually seems to be conflicting.

It seems to be a conflict with `Optifine 1.12.2 HD U C7`. Not sure if it's specific to this version of Optifine or if it's been an issue for a while.

**Comment by iChun** [comment]
Oh lovely. Optifine... Again. Anyways I'll work on a fix or something, let me know how it goes. It'll probably break the mod to be honest but it won't crash. Just.... a really unnecessary check. Try the next version of iChunUtil when it's released.

**Comment by iChun** [comment]
Should be v7.1.4.

**Comment by Snuggle** [comment]
This issue still occurs with `iChunUtil-1.12.2-7.1.4.jar`.

New Crash-log: https://pastebin.com/6wPgm0gT (Same error, unrelated mods removed.)

(Also, thank you for responding so gosh-darn quickly!)

Just because I can, here's a recording of the bug: https://www.youtube.com/watch?v=y8Ze-ohvpBM

**=====================**

On an unrelated note, I wish Curse Forge was above 9minecraft on Google. This is probably why I downloaded it from them. 🙁
![image](https://user-images.githubusercontent.com/26250962/34145348-8dc892c0-e48d-11e7-8be0-f1e1ca6c7a4b.png)

**Comment by Snuggle** [comment]
@iChun I’m not sure if you’re not receiving notifications, so here’s a tag. I don’t have permission to re-open this issue. :p

**Comment by CcytherR** [comment]
just a heads up, but still seems to be an issue it seems, i just crashed just now https://pastebin.com/AN6Msp9G

**Comment by iChun** [comment]
Due to the age of this issue (and that I no longer support my mods for 1.12.2 and older) I am closing this issue. My apologies we weren't able to work out a fix
